// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * walking_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_mono_frame_10_png);    // assets/mono_frame_10.png
LV_IMG_DECLARE(ui_img_mono_frame_11_png);    // assets/mono_frame_11.png
LV_IMG_DECLARE(ui_img_mono_frame_12_png);    // assets/mono_frame_12.png
LV_IMG_DECLARE(ui_img_mono_frame_13_png);    // assets/mono_frame_13.png
LV_IMG_DECLARE(ui_img_mono_frame_14_png);    // assets/mono_frame_14.png
LV_IMG_DECLARE(ui_img_mono_frame_15_png);    // assets/mono_frame_15.png
LV_IMG_DECLARE(ui_img_mono_frame_16_png);    // assets/mono_frame_16.png
LV_IMG_DECLARE(ui_img_mono_frame_17_png);    // assets/mono_frame_17.png
LV_IMG_DECLARE(ui_img_mono_frame_18_png);    // assets/mono_frame_18.png
LV_IMG_DECLARE(ui_img_mono_frame_19_png);    // assets/mono_frame_19.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font18);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
