// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Laps = NULL;
lv_obj_t * ui_Ldist = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_mono_frame_10_png);
    lv_obj_set_width(ui_Image3, 32);
    lv_obj_set_height(ui_Image3, 32);
    lv_obj_set_x(ui_Image3, -53);
    lv_obj_set_y(ui_Image3, 0);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Laps = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Laps, 100);
    lv_obj_set_height(ui_Laps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Laps, 10);
    lv_obj_set_y(ui_Laps, -21);
    lv_obj_set_align(ui_Laps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Laps, "APs:");
    lv_obj_set_style_text_color(ui_Laps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Laps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Laps, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ldist = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Ldist, 100);
    lv_obj_set_height(ui_Ldist, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ldist, 10);
    lv_obj_set_y(ui_Ldist, -9);
    lv_obj_set_align(ui_Ldist, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ldist, "Dist:");
    lv_obj_set_style_text_color(ui_Ldist, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ldist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ldist, &ui_font_Font18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image3 = NULL;
    ui_Laps = NULL;
    ui_Ldist = NULL;

}
